---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: shipos
  namespace: websites
spec:
  selector:
    matchLabels:
      name: shipos
  template:
    metadata:
      labels:
        name: shipos
    spec:
      containers:
      - name: shipos
        image: dolittle/shipos
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 100Mi          
